title: 'Epsilon Academics'
default_lang: en
author:
  name: 'Manish Balamurugan'
  email: manishbalamurugan@gmail.com
taxonomies:
  - category
  - tag
  - author
metadata:
  description: 'We are an entirely student run educational nonprofit organization that promotes STEM initiative and learning to students in Northern Virginia and the Washington Metropolitan Area.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
