enabled: true
footer-text: '© Copyright EPSILON ACADEMICS 2019'
footer-design: 'Design by Manish Balamurugan'
footer-social:
  -
    socialIconClass: 'fa fa-facebook-square'
    socialIconText: Facebook
    socialIconLink: 'https://www.facebook.com/epsilonacademics'
  -
    socialIconClass: 'fa fa-twitter'
    socialIconText: Twitter
    socialIconLink: 'https://twitter.com/epsilonacademic'
  -
    socialIconClass: 'fa fa-instagram'
    socialIconText: Instagram
    socialIconLink: 'https://www.instagram.com/epsilonacademics/'
  -
    socialIconClass: 'fa fa-linkedin'
    socialIconText: LinkedIn
    socialIconLink: 'https://www.linkedin.com/in/manishbalamurugan/'
footer-additional-text: 'Fairfax High School'
custom_logo:
  user/themes/hola/images/logo/finlogo.png:
    name: finlogo.png
    type: image/png
    size: 57603
    path: user/themes/hola/images/logo/finlogo.png
